--TIPO CONTATO
/*CREATE TABLE DDI_BGM(
ID_DDI INT NOT NULL PRIMARY KEY IDENTITY(1,1),
DDI VARCHAR(3) NOT NULL,)

CREATE TABLE DDD_BGM(
ID_DDD INT NOT NULL PRIMARY KEY IDENTITY(1,1),
DDD VARCHAR(3) NOT NULL
)

CREATE TABLE TELEFONE_BGM(
IDTEL INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NUMERO VARCHAR(9) NOT NULL,
ID_DDD VARCHAR(3) NOT NULL,
CONSTRAINT Fk_DDD FOREIGN KEY (IDTEL) REFERENCES DBO.DDD_BGM (ID_DDD),
CONSTRAINT FK_DDI FOREIGN KEY (IDTEL) REFERENCES DBO.DDI_BGM (ID_DDI)
)

CREATE TABLE EMAIL_BGM(
ID_EMAIL INT NOT NULL PRIMARY KEY IDENTITY(1,1),
EMAIL VARCHAR(50) NOT NULL,
)

CREATE TABLE TIPOCONTATO (
ID_TIPO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDTEL INT NULL,
ID_EMAIL INT NULL,
CONSTRAINT Fk_TEL FOREIGN KEY (ID_TIPO) REFERENCES DBO.TELEFONE_BGM (IDTEL),
CONSTRAINT Fk_EMAIL FOREIGN KEY (ID_TIPO) REFERENCES DBO.EMAIL_BGM (ID_EMAIL)
)
*/

/*
CREATE TABLE DBO.ESTADO_BGM(
IDESTADO INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(3)
)

CREATE TABLE DBO.BAIRRO_BGM(
IDBAIRRO INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(50)
)

CREATE TABLE DBO.CIDADE_BGM(
IDCIDADE INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(50)
)

CREATE TABLE DBO.RUA_BGM(
IDRUA INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(100)
)

CREATE TABLE DBO.ENDERECO_BGM (
IDENDERECO INT PRIMARY KEY IDENTITY(1,1),
IDESTADO INT NOT NULL,
IDBAIRRO INT NOT NULL,
IDCIDADE INT NOT NULL,
IDRUA INT NOT NULL,
COMPLEMENTO VARCHAR(50),
NUMERO INT

CONSTRAINT FK_ENDERECO_ESTADO FOREIGN KEY (IDESTADO)
REFERENCES DBO.ESTADO_BGM(IDESTADO),
CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY (IDBAIRRO)
REFERENCES DBO.BAIRRO_BGM(IDBAIRRO),
CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY (IDCIDADE)
REFERENCES DBO.CIDADE_BGM(IDCIDADE),
CONSTRAINT FK_ENDERECO_RUA FOREIGN KEY (IDRUA)
REFERENCES DBO.RUA_BGM(IDRUA)
)
*/

/*FISICO/JURÍDIO 
- NOME, CPF/CNPJ, RG, TIPOCONTATO, ENDEREÇO*/

/*
CREATE TABLE USUARIO_BGM(
ID_USUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
FISC_JURID BIT NOT NULL,--FISICO 0 , JURIDICO 1
NOME VARCHAR(100) NULL,
CPF VARCHAR(11) NULL,
CNPJ VARCHAR(14) NULL,
CNH VARCHAR(11) NULL,
RENAVAN VARCHAR(11) NULL,
ID_TIPOCONTATO INT NULL,
ID_ENDERECO INT NULL,
CONSTRAINT FK_TIPOCONTATO FOREIGN KEY (ID_UDUARIO)
REFERENCES DBO.TIPOCONTATO(ID_TIPO)
)*/